---
packages:
  - name: alerts
    path: pkg/alerts
    types:
      - name: AlertsMutingRuleConditionInput
      - name: AlertsMutingRuleInput
      - name: AlertsPoliciesSearchCriteriaInput
      - name: AlertsPoliciesSearchResultSet
      - name: AlertsPolicy
      - name: AlertsPolicyInput
      - name: AlertsPolicyUpdateInput
      - name: AlertsNrqlConditionTermsOperator
    # providers:
    #   - name: typegen
    #     destination_file: types.go
    #
