---
# Log level for running tutone
# Default: info
log_level: debug

# Cache for storing a GraphQL schema
cache:
  # Default: schema.json
  schema_file: schema.json

# GraphQL endpoint to query for schema
# Required
endpoint: https://api.newrelic.com/graphql

# How to authenticate to the API
auth:
  # Header set with the API key for authentication
  # Default: Api-Key
  header: Api-Key

  # Environment variable to get the API key from
  # Default: TUTONE_API_KEY
  api_key_env_var: NEW_RELIC_API_KEY

packages:
  - name: accounts
    path: pkg/accounts
    import_path: github.com/newrelic/newrelic-client-go/pkg/accounts
    generators:
      - typegen
    imports:
      - github.com/newrelic/newrelic-client-go/pkg/nrtime
    types:
      - name: AccountOutline
      - name: AccountReference
      - name: RegionScope

      #
      # Types that we should auto-detect are in another package someday
      #
      - name: EpochMilliseconds
        field_type_override: nrtime.EpochMilliseconds
        skip_type_create: true
      - name: TimeWindowInput
        field_type_override: nrtime.TimeWindowInput
        skip_type_create: true


  - name: alerts
    path: pkg/alerts
    import_path: github.com/newrelic/newrelic-client-go/pkg/alerts
    generators:
      - typegen
    imports:
      - github.com/newrelic/newrelic-client-go/pkg/apiaccess
    types:
      - name: AlertsMutingRuleConditionInput
      - name: AlertsMutingRuleInput
      - name: AlertsMutingRuleScheduleInput
      - name: AlertsNrqlConditionTermsOperator
      - name: AlertsPoliciesSearchCriteriaInput
      - name: AlertsPoliciesSearchResultSet
      - name: AlertsPolicy
      - name: AlertsPolicyInput
      - name: AlertsPolicyUpdateInput
      - name: ID
        field_type_override: string
        skip_type_create: true

      #
      # Types that we should auto-detect are in another package someday
      #
      - name: NaiveDateTime
        field_type_override: nrtime.NaiveDateTime
        skip_type_create: true


  - name: apiaccess
    path: pkg/apiaccess
    import_path: github.com/newrelic/newrelic-client-go/pkg/apiaccess
    generators:
      - typegen
    types:
      - name: ApiAccessActorStitchedFields
      - name: ApiAccessCreateIngestKeyInput
      - name: ApiAccessCreateInput
      - name: ApiAccessCreateKeyResponse
      - name: ApiAccessCreateUserKeyInput
      - name: ApiAccessDeleteInput
      - name: ApiAccessDeleteKeyResponse
      - name: ApiAccessIngestKeyErrorType
      - name: ApiAccessIngestKeyType
      - name: ApiAccessKey # gql interface
      - name: APIAccessKeyError
        interface_methods:
          - "GetError() error"
      - name: ApiAccessKeySearchQuery
      - name: ApiAccessKeySearchResult
      - name: ApiAccessKeySearchScope
      - name: ApiAccessKeyType
      - name: ApiAccessUpdateIngestKeyInput
      - name: ApiAccessUpdateInput
      - name: ApiAccessUpdateKeyResponse
      - name: ApiAccessUpdateUserKeyInput
      - name: ApiAccessUserKeyErrorType
      # This must be a string, as where ID is used the type is a string...
      - name: ID
        field_type_override: string
        skip_type_create: true


  - name: cloud
    path: pkg/cloud
    imports:
      - github.com/newrelic/newrelic-client-go/pkg/nrtime
      - encoding/json
      - fmt
    generators:
      - typegen
      - nerdgraphclient
    queries:
      - path: ["actor", "cloud"]
        endpoints:
          - name: linkedAccounts
            max_query_field_depth: 2
            include_nullable: true
    mutations:
      - name: cloudConfigureIntegration
        max_query_field_depth: 1
      - name: cloudDisableIntegration
        max_query_field_depth: 1
      - name: cloudLinkAccount
        max_query_field_depth: 1
        argument_type_overrides:
          accountId: "Int!"
          accounts: "CloudLinkCloudAccountsInput!"
      - name: cloudRenameAccount
        max_query_field_depth: 1
        argument_type_overrides:
          accountId: "Int!"
          accounts: "[CloudRenameAccountsInput!]!"
      - name: cloudUnlinkAccount
        max_query_field_depth: 1
    types:
      #
      # Types that we should auto-detect are in another package someday
      #
      - name: EpochSeconds
        field_type_override: nrtime.EpochSeconds
        skip_type_create: true
      - name: EpochMilliseconds
        field_type_override: nrtime.EpochMilliseconds
        skip_type_create: true


  - name: edge
    path: pkg/edge
    import_path: github.com/newrelic/newrelic-client-go/pkg/edge
    generators:
      - typegen
    types:
      - name: EdgeAccountStitchedFields
      - name: EdgeAgentEndpointDetail
      - name: EdgeCreateTraceObserverInput
      - name: EdgeCreateTraceObserverResponse
      - name: EdgeCreateTraceObserverResponseError
      - name: EdgeCreateTraceObserverResponseErrorType
      - name: EdgeCreateTraceObserverResponses
      - name: EdgeDeleteTraceObserverInput
      - name: EdgeDeleteTraceObserverResponse
      - name: EdgeDeleteTraceObserverResponseError
      - name: EdgeDeleteTraceObserverResponseErrorType
      - name: EdgeDeleteTraceObserverResponses
      - name: EdgeEndpoint
      - name: EdgeEndpointStatus
      - name: EdgeEndpointType
      - name: EdgeHttpsEndpointDetail
      - name: EdgeProviderRegion
      - name: EdgeTraceObserver
      - name: EdgeTraceObserverResponse
      - name: EdgeTraceObserverResponseError
      - name: EdgeTraceObserverResponseErrorType
      - name: EdgeTraceObserverStatus
      - name: EdgeTracing


  - name: entities
    path: pkg/entities
    import_path: github.com/newrelic/newrelic-client-go/pkg/entities
    generators:
      - typegen
      - nerdgraphclient
    imports:
      - github.com/newrelic/newrelic-client-go/pkg/accounts
      - github.com/newrelic/newrelic-client-go/pkg/nrtime
    queries:
      - path: ["actor"]
        endpoints:
          - name: entities
            max_query_field_depth: 2
          - name: entity
            max_query_field_depth: 2
          - name: entitySearch
            max_query_field_depth: 2
            include_nullable: true
    mutations:
      - name: taggingAddTagsToEntity
        max_query_field_depth: 1

    types:
      - name: AttributeMap
        create_as: "map[string]interface{}"

      # Types this package owns
      - name: AlertableEntity
      - name: ApmApplicationEntity
      - name: ApmBrowserApplicationEntity
      - name: ApmDatabaseInstanceEntity
      - name: ApmExternalServiceEntity
      - name: BrowserApplicationEntity
      - name: CollectionEntity
      - name: DashboardEntity
      - name: Entity
      - name: EntityGuid
      - name: EntityOutline
      - name: EntityRelationship
      - name: EntityRelationshipFilter
      - name: EntityRelationshipNode
      - name: EntityRelationshipType
      - name: EntitySearch
      - name: EntitySearchCounts
      - name: EntitySearchCountsFacet
      - name: EntitySearchOptions
      - name: EntitySearchQueryBuilder
      - name: EntitySearchResult
      - name: EntitySearchSortCriteria
      - name: EntitySearchTypes
      - name: EntityTag
      - name: EntityTagValueWithMetadata
      - name: EntityTagWithMetadata
      - name: EntityType
      - name: GenericEntity
      - name: GenericEntityOutline
      - name: GenericInfrastructureEntity
      - name: InfrastructureAwsLambdaFunctionEntity
      - name: InfrastructureHostEntity
      - name: InfrastructureIntegrationEntity
      - name: MobileApplicationEntity
      - name: SyntheticMonitorEntity
      - name: ThirdPartyServiceEntity
      - name: UnavailableEntity
      - name: UnavailableEntityOutline
      - name: WorkloadEntity

      #
      # Types that our other packages define
      #   TODO: Fix tutone to figure this out for us
      #
      - name: AccountOutline
        field_type_override: accounts.AccountOutline
        skip_type_create: true
      - name: AccountReference
        field_type_override: accounts.AccountReference
        skip_type_create: true
      - name: DateTime
        field_type_override: nrtime.DateTime
        skip_type_create: true
      - name: EpochMilliseconds
        field_type_override: nrtime.EpochMilliseconds
        skip_type_create: true
      - name: Minutes
        field_type_override: nrtime.Minutes
        skip_type_create: true
      - name: Seconds
        field_type_override: nrtime.Seconds
        skip_type_create: true


  - name: eventstometrics
    path: pkg/eventstometrics
    import_path: github.com/newrelic/newrelic-client-go/pkg/eventstometrics
    generators:
      - typegen
    imports:
      - github.com/newrelic/newrelic-client-go/pkg/nrtime
    types:
      - name: EventsToMetricsAccountStitchedFields
      - name: EventsToMetricsCreateRuleFailure
      - name: EventsToMetricsCreateRuleInput
      - name: EventsToMetricsCreateRuleResult
      - name: EventsToMetricsCreateRuleSubmission
      - name: EventsToMetricsDeleteRuleFailure
      - name: EventsToMetricsDeleteRuleInput
      - name: EventsToMetricsDeleteRuleResult
      - name: EventsToMetricsDeleteRuleSubmission
      - name: EventsToMetricsErrorReason
      - name: EventsToMetricsListRuleResult
      - name: EventsToMetricsRule
      - name: EventsToMetricsUpdateRuleFailure
      - name: EventsToMetricsUpdateRuleInput
      - name: EventsToMetricsUpdateRuleResult
      - name: EventsToMetricsUpdateRuleSubmission
      - name: ID
        field_type_override: string
        skip_type_create: true

      #
      # Types that we should auto-detect are in another package someday
      #
      - name: DateTime
        field_type_override: nrtime.DateTime
        skip_type_create: true


  - name: nerdstorage
    path: pkg/nerdstorage
    import_path: github.com/newrelic/newrelic-client-go/pkg/nerdstorage
    generators:
      - typegen
    types:
      - name: NerdStorageCollectionMember
      - name: NerdStorageDocument
      - name: NerdStorageEntityScope
      - name: NerdStorageScope
      - name: NerdStorageScopeInput


  - name: nrdb
    path: pkg/nrdb
    import_path: github.com/newrelic/newrelic-client-go/pkg/nrdb
    generators:
      - typegen
    imports:
      - github.com/newrelic/newrelic-client-go/pkg/nrtime
    types:
      - name: Nrql
        create_as: string
      - name: NRDBMetadataTimeWindow
      - name: NRDBResult
        create_as: map[string]interface{}
      - name: NrqlHistoricalQuery
      - name: SuggestedNRQLQuery
      - name: NrdbResultContainer
      - name: EventDefinition

      #
      # Types that we should auto-detect are in another package someday
      #
      - name: EpochSeconds
        field_type_override: nrtime.EpochSeconds
        skip_type_create: true
      - name: EpochMilliseconds
        field_type_override: nrtime.EpochMilliseconds
        skip_type_create: true
      - name: TimeWindowInput
        field_type_override: nrtime.TimeWindowInput
        skip_type_create: true


  - name: nrtime
    path: pkg/nrtime
    import_path: github.com/newrelic/newrelic-client-go/pkg/nrtime
    generators:
      - typegen
    imports:
      - github.com/newrelic/newrelic-client-go/internal/serialization
    types:
      - name: DateTime
        create_as: string
      - name: EpochMilliseconds
        create_as: serialization.EpochTime
      - name: EpochSeconds
        create_as: serialization.EpochTime
      - name: Minutes
        create_as: string
      - name: NaiveDateTime
        create_as: string
      - name: Seconds
        create_as: string
      - name: TimeWindowInput



generators:
  - name: typegen
    fileName: "types.go"
  - name: nerdgraphclient
    fileName: "{{.PackageName}}_api.go"

