---
package_type_map:
  alerts:
    - AlertsMutingRuleConditionInput
    - AlertsMutingRuleInput
    - AlertsPoliciesSearchCriteriaInput
    - AlertsPoliciesSearchResultSet
    - AlertsPolicy
    - AlertsPolicyInput
    - AlertsPolicyUpdateInput
